name: workflow-practice1
on:
  push:
    branches: [main]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: use echo command
        run: echo "Hello workflow!!"
      - name: use my command
        run: sh $GITHUB_WORKSPACE/sh/test.sh